### ISSUE TITLE
URL not correctly found while validating h-entry

### ISSUE THREAD

**Issue by djc** [indieweb/indiewebify-me#40]
When testing my site, here:

http://indiewebify.me/validate-h-entry/?url=https%3A%2F%2Fdirkjan.ochtman.nl%2F

The u-url class used in the title links is not found for some reason. Spec problem, or validator problem?

**Comment by elimisteve** [comment]
@djc That link now shows `Success! We found the following post h-entry on your site: ...`.  Is there no issue now, then?

**Comment by djc** [comment]
The issue is still there from my perspective. It says "Add a URL!", whereas I would contend that the URL is already specified, according to spec.

**Comment by voxpelli** [comment]
@djc Looks like you are using Microformats 1 and `hentry`-properties rather than Microformats 2 and `h-entry`-properties. That means that parsers that don't fully support Microformats 1, as the Indiewebify parser doesn't seem to be doing, won't fully understand your site. I would suggest upgrading to Microformats 2.

For reference – the PHP Microformats parser doesn't recognize rel-bookmark URL:s as `u-url`:s (your site currently use `rel="bookmark"` rather than `class="u-url"`– which is correct for you as that's what one should use when using Microformats 1): http://pin13.net/mf2/?url=https://dirkjan.ochtman.nl/

But the Node.js library do: http://glennjones.net/tools/microformats/?url=https%3A%2F%2Fdirkjan.ochtman.nl%2F&callback=&dateformat=auto

**Comment by djc** [comment]
I have both `rel="bookmark"` and `class="u-url"`, I think?

Anyway, I tried adding `class="h-entry"` to my `article` elements, and it indiewebify.me still doesn't seem to find the `u-url` property.

**Comment by voxpelli** [comment]
@djc I don't see any mentions of `u-url` in the source of your site :confused:

See this screenshot:

![2015-07-31 at 19 06](https://cloud.githubusercontent.com/assets/34457/9012705/55fcb0c2-37b7-11e5-8040-b76fa8840dd3.png)

**Comment by djc** [comment]
Doh, you're right. Apparently I have much the same markup in two different templates. :( Thanks for the explanation about microformats versions!
