### ISSUE TITLE
Dead End:   2. Set up Web Sign In

### ISSUE THREAD

**Issue by jmayersf** [indieweb/indiewebify-me#48]
After we ran the test on this step, the rest of the page disappeared and we were not able to proceed directly to step 3

**Comment by rikmendes** [comment]
This is what I get when trying level 2 : 

![screenshot_69](https://cloud.githubusercontent.com/assets/12155003/13723545/1096b1c8-e869-11e5-9966-61d3b13ac4c0.png)

**Comment by gRegorLove** [comment]
@jmayersf @rikmendes Are you referring to this step? http://indiewebify.me/validate-rel-me/ What domain(s) are you entering that cause it to return a blank page?

**Comment by gRegorLove** [comment]
I [reached out](https://gregorlove.com/2016/09/rikmende-can-you-let-me/) to @rikmendes and neither of us were able to duplicate this error currently. Since it looks like it could have been a temporary network issue at the time and there's been a few deployments since this report, I'm going to close it for now.

**Comment by rikmendes** [comment]
correct, it was a network issue !
