### ISSUE TITLE
Sites that link to an http URL that later gets upgraded to https give 400

### ISSUE THREAD

**Issue by kevinmarks** [indieweb/indiewebify-me#54]
eg
http://indiewebify.me/rel-me-links/?url1=http%3A%2F%2Ftantek.com%2F&url2=http%3A%2F%2Fflickr.com%2Ftantek%2F 

http://indiewebify.me/rel-me-links/?url1=http%3A%2F%2Ftantek.com%2F&url2=http%3A%2F%2Fwww.facebook.com%2Ftantek.celik 

http://indiewebify.me/rel-me-links/?url1=http%3A%2F%2Ftantek.com%2F&url2=http%3A%2F%2Ffoursquare.com%2Ft

**Comment by kevinmarks** [comment]
bonus points: https://indiewebify.me/rel-me-links/?url1=https%3A%2F%2Ftwitter.com%2Frandileeharper&url2=https%3A%2F%2Ft.co%2FOWOqcXQCyx

Inbound rel-me URL redirects insecurelyArray ( [0] => http://blog.randi.io )

https://indiewebify.me/rel-me-links/?url1=https%3A%2F%2Ftwitter.com%2Frandileeharper&url2=http%3A%2F%2Ft.co%2FOWOqcXQCyx

Inbound rel-me URL redirects insecurelyArray ( [0] => http://blog.randi.io [1] => https://blog.randi.io/ )

o_O

**Comment by gRegorLove** [comment]
I'm not sure what the correct behavior is here. Looks like it was set up this way to return a 400 so the AJAX would display "couldn't be fetched" on the rel-me check. Should there be some kind of warning that you've linked to http instead of https?

The second set of examples it looks like url1 and url2 parameters are backwards. url1 is supposed to be your domain, url2 is supposed to be the external profile. Swapping them I get "true" for the first example, "false" for the second.

**Comment by kevinmarks** [comment]
Yes, but I'm now checking rel-me both ways tasks to my browser plugin
