### ISSUE TITLE
false negative testing https://try.gogs.io/issue-5008

### ISSUE THREAD

**Issue by mro** [indieweb/indiewebify-me#78]
https://indiewebify.me/validate-rel-me/?url=https%3A%2F%2Ftry.gogs.io%2Fissue-5008 IMO falsely gives

> https://l.mro.name/o/p/ does not link back

while https://l.mro.name/o/p/ has both a HTTP `Link: ` response-header and a `<link rel="me" href="http...`.

P.S.: maybe related to https://github.com/indieweb/verify-me/issues/4 and https://github.com/gogs/gogs/issues/5008

**Comment by gRegorLove** [comment]
The indieweb/rel-me library uses the PHP [microformats parser](https://github.com/microformats/php-mf2) to parse rel values. It doesn't support XML documents currently, so it's not finding the rels on l.mro.name.

**Comment by mro** [comment]
@gRegorLove thx. That's a sad surprise. Is the indieweb really microformats only?

**Comment by gRegorLove** [comment]
The php-mf2 parser is geared towards parsing HTML currently, though I've brought this topic up in chat so we might expand it, if possible.

Another alternative might be to expand the [indieweb/rel-me](https://github.com/indieweb/rel-me) library to parse `rel` from headers or other document types. Currently it only uses php-mf2 to parse documents, so it has that limitation.

**Comment by Zegnat** [comment]
I’ve had another long look at how `rel` values are currently being extracted, together with/parallel to @sknebel. The PHP mf2 parser can actually parse the page without any problems. This may still not be 100% correct, but because Atom happens to use the same `<link>` format as HTML the current XPaths Just Work™. But…

* the parser will [not pass non-HTML files to the parser](https://github.com/microformats/php-mf2/blob/00b70ee7eb7f5b0585b1bd467f6c9cbd75055d23/Mf2/Parser.php#L79-L82) when it is retrieving them from a URL; and
* the parser does not currently support gzip’ed content so even with that check disabled it is incapable of parsing https://l.mro.name/o/p/.

These should probably be two separate bugs on the parser.

Note that the second point may also be a problem with @mro’s server. When I specify `Accept-Encoding: identity` it will return gzip, even when I specifically add `gzip;q=0` which is supposed to disallow it.

**Comment by mro** [comment]
@Zegnat 

> Looks like you have found yourself a nice little edge-case here!

lol, indeed, but isn't the @indieweb an edge-case by it's very nature?

> a problem with @mro’s server. When I specify Accept-Encoding: identity it will return gzip, even when I specifically add gzip;q=0 which is supposed to disallow it.

aaaah, yes, I prepare static content for 0-computation delivery and compress for storage (and bandwith) efficiency.

So I currently don't care about `Accept` which I prbly shpud, but am not sure what to think about yet.

**Comment by mro** [comment]
P.S.: If my (devuan/jessie) lighttpd (1.4.45) would let me without hassle, I would return [HTTP 406](https://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html#sec10.4.7) instead of the current

    $ curl --location --silent --header 'Accept-Encoding: identity' https://l.mro.name/ | file -
    /dev/stdin: gzip compressed data, max compression
